services:
  postgres:
    image: postgres:14
    container_name: postgres-bank
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bank_transactions
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finance-tracker-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: finance-tracker-backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: bank_transactions
      NODE_ENV: development
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - finance-tracker-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: finance-tracker-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - finance-tracker-network
    restart: unless-stopped
    
  adminer:
    image: adminer
    container_name: adminer-finance-tracker
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - finance-tracker-network
    restart: unless-stopped

networks:
  finance-tracker-network:
    driver: bridge

volumes:
  postgres_data: 